### ISSUE TITLE
Icons are not displayed

### ISSUE THREAD

**Issue by alexbofa** [wywywywy/sd-webui-depth-lib#5]
Hello, can you help me? How can this be fixed? Thanks

**Describe the bug**
I wrote about the problem in the original hub, https://github.com/jexom/sd-webui-depth-lib/issues/36#issuecomment-1669528039 https://github.com/jexom/sd-webui-depth-lib/issues/36#issuecomment-1669541982

**Environment**
Put x in the brackets to select
- [x] Local desktop ([1.5.1](https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases/tag/v1.5.1), [1.5.2](https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases/tag/v1.5.2)) [Portable Stable Diffusion](https://github.com/serpotapov/stable-diffusion-portable)
- [ ] Colab

**Comment by wywywywy** [comment]
Sorry for delay. I turned off notifications by mistake.

But no I don't know why either. Does this problem still exist in WebUI v1.6? It's now using a much newer version of Gradio.

**Comment by wywywywy** [comment]
Also worth trying is to use a "hard link" (aka junction) rather than a standard soft link.
